spring.datasource.url=${DB_URL_PROD:jdbc:mysql://localhost:3306/shopeeerp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
spring.datasource.username=${DB_USERNAME_PROD:root}
spring.datasource.password=${DB_PASSWORD_PROD:change-me}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=20

app.log.path=/var/log/shopeeerp
