spring.datasource.url=${DB_URL_TEST:jdbc:mysql://localhost:3306/shopeeerp_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
spring.datasource.username=${DB_USERNAME_TEST:root}
spring.datasource.password=${DB_PASSWORD_TEST:su123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10

app.log.path=logs/test
