CREATE TABLE IF NOT EXISTS ozon_posting (
    posting_number VARCHAR(50) PRIMARY KEY,
    shop_id BIGINT,
    order_id BIGINT,
    order_number VARCHAR(50),
    status VARCHAR(50),
    substatus VARCHAR(80),
    tpl_integration_type VARCHAR(30),
    delivery_method_id BIGINT,
    delivery_method_name VARCHAR(200),
    warehouse_id BIGINT,
    warehouse_name VARCHAR(200),
    tpl_provider_id BIGINT,
    tpl_provider_name VARCHAR(200),
    tracking_number VARCHAR(120),
    in_process_at DATETIME,
    shipment_date DATETIME,
    shipment_date_without_delay DATETIME,
    delivering_date DATETIME,
    is_express BIT,
    customer_json LONGTEXT,
    addressee_json LONGTEXT,
    barcodes_json LONGTEXT,
    analytics_json LONGTEXT,
    financial_json LONGTEXT,
    optional_json LONGTEXT,
    cancellation_json LONGTEXT,
    requirements_json LONGTEXT,
    tariffication_json LONGTEXT,
    available_actions LONGTEXT,
    last_changed_at DATETIME,
    raw_payload LONGTEXT,
    created_at DATETIME,
    updated_at DATETIME
);

CREATE TABLE IF NOT EXISTS ozon_posting_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    posting_number VARCHAR(50),
    sku BIGINT,
    offer_id VARCHAR(100),
    name VARCHAR(500),
    currency_code VARCHAR(10),
    price DECIMAL(18,6),
    quantity INT,
    imei LONGTEXT,
    created_at DATETIME,
    updated_at DATETIME,
    CONSTRAINT fk_ozon_posting_item_posting FOREIGN KEY (posting_number) REFERENCES ozon_posting(posting_number)
);
