CREATE TABLE IF NOT EXISTS ozon_order (
    id BIGINT PRIMARY KEY,
    order_number VARCHAR(64),
    shipment_number VARCHAR(64),
    store VARCHAR(64),
    amount DECIMAL(12,2),
    ozon_tax DECIMAL(12,2),
    cost DECIMAL(12,2),
    profit DECIMAL(12,2),
    package_info VARCHAR(128),
    quantity INT,
    purchase_no VARCHAR(64),
    domestic_no VARCHAR(64),
    weight DECIMAL(10,3),
    tracking_no VARCHAR(64),
    logistics_type VARCHAR(64),
    ship_status VARCHAR(32),
    status VARCHAR(32),
    sub_status VARCHAR(32),
    order_time DATETIME,
    image_url VARCHAR(512),
    detail TEXT,
    currency VARCHAR(8),
    created_at DATETIME,
    updated_at DATETIME,
    sync_time DATETIME
);

CREATE TABLE IF NOT EXISTS ozon_order_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id BIGINT,
    product_id BIGINT,
    offer_id VARCHAR(128),
    name VARCHAR(512),
    image_url VARCHAR(512),
    quantity INT,
    price DECIMAL(12,2),
    tax DECIMAL(12,2),
    cost DECIMAL(12,2),
    profit DECIMAL(12,2),
    weight DECIMAL(10,3),
    tracking_no VARCHAR(64),
    status VARCHAR(32),
    sub_status VARCHAR(32),
    created_at DATETIME,
    updated_at DATETIME,
    CONSTRAINT fk_ozon_order_item_order FOREIGN KEY (order_id) REFERENCES ozon_order(id)
);
